"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var mobile_1 = require("./mobile");
var mobile1 = new mobile_1.Mobile("Apple", "iPhone", "14", "amarillo", 900);
console.log(mobile1.getName());
console.log(mobile1.getTrademark());
console.log(mobile1.getModel());
console.log(mobile1.getColor());
console.log(mobile1.getPrice());
mobile1.setName("Samsung");
mobile1.setTrademark("Galaxy");
mobile1.setModel("S21");
mobile1.setColor("rosa");
mobile1.setPrice(300);
console.log(mobile1.getName());
console.log(mobile1.getTrademark());
console.log(mobile1.getModel());
console.log(mobile1.getColor());
console.log(mobile1.getPrice());
